In [2]:
#Import Libraries 
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
#Check Tensorflow version
tf.__version__

'2.4.0'

In [7]:
#Importing the data set [Create x: contain the independent variable, y: contain the dependent variable]
dataset = pd.read_excel('Folds5x2_pp.xlsx')
x = dataset.iloc[:, : -1].values
y = dataset.iloc[:, -1].values

In [8]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [10]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [11]:
#Splitting the dataset into test and traning
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [12]:
#Initializing the ANN
ann = tf.keras.models.Sequential()

In [15]:
#Adding input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#Adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
#Adding the output layer (No activation funtion due to expected result in real number)
ann.add(tf.keras.layers.Dense(units=1))

In [17]:
#Compiling the ANN
ann.compile(optimizer='adam', loss='mean_squared_error')

In [18]:
ann.fit(x_train, y_train, batch_size = 32, epochs=100 )

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 77152.8638
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 681.5402
Epoch 3/100
240/240 [==============================] - 0s 960us/step - loss: 644.7067
Epoch 4/100
240/240 [==============================] - 0s 974us/step - loss: 602.3247
Epoch 5/100
240/240 [==============================] - 0s 946us/step - loss: 530.4627
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 477.9038
Epoch 7/100
240/240 [==============================] - 0s 997us/step - loss: 406.5600
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 357.2554
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 299.0484
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 252.9316
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 204.1961
Epoch 12/100
240/240 [==============================] - 0s 952us

In [20]:
#Prediction
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[431.39 431.23]
 [462.42 460.01]
 [465.9  461.14]
 ...
 [473.18 473.26]
 [439.88 438.  ]
 [459.14 463.28]]
