<a href="https://colab.research.google.com/github/Denuwanhh/neural-network-notebooks/blob/main/Ex_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Import required libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
#Check The version of Tensorflow
tf.__version__

'2.4.0'

In [ ]:
##Data Preprocessing

#Import Dataset
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
#Encode Data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

#Ecode data : Gender
x[:,2] = le.fit_transform(x[:,2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
#One Hot Encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#One Hot Encoding: Geo
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


In [ ]:
#Spliting the dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

print('x_train: ' + str(len(x_train)))
print('x_test: ' + str(len(x_test)))
print('y_train: ' + str(len(y_train)))
print('y_test: ' + str(len(y_test)))

x_train: 8000
x_test: 2000
y_train: 8000
y_test: 2000


In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

print('Train Data Set : \n')
print(x_train)
print('Test Data Set : \n')
print(x_test)

Train Data Set : 

[[ 0.5698444  -0.5698444  -1.01460667 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.75486502  1.75486502 -1.01460667 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.5698444  -0.5698444   0.98560362 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.5698444  -0.5698444   0.98560362 ...  0.64259497 -1.03227043
   1.41231994]
 [ 0.5698444  -0.5698444  -1.01460667 ...  0.64259497  0.9687384
   0.84432121]
 [-1.75486502  1.75486502 -1.01460667 ...  0.64259497 -1.03227043
   0.32472465]]
Test Data Set : 

[[-1.62776996  1.62776996 -0.95692675 ...  0.66011376  0.97628121
   1.62185911]
 [ 0.61433742 -0.61433742  1.04501206 ...  0.66011376 -1.02429504
   0.504204  ]
 [ 0.61433742 -0.61433742 -0.95692675 ...  0.66011376  0.97628121
  -0.41865644]
 ...
 [ 0.61433742 -0.61433742 -0.95692675 ...  0.66011376 -1.02429504
   0.72775202]
 [-1.62776996  1.62776996 -0.95692675 ...  0.66011376  0.97628121
  -1.54162886]
 [-1.62776996  1.62776996 -0.95692675 ...  0.66011376 -1.024295

In [ ]:
#Initiate ANN
ann = tf.keras.models.Sequential()

In [ ]:
#Add input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
#Add second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
#Add output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
#Trainning the ANN
#Compile
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])

In [ ]:
#Train the ANN
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.9049 - accuracy: 0.2059
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7248 - accuracy: 0.2827
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6367 - accuracy: 0.7962
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5891 - accuracy: 0.7897
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5562 - accuracy: 0.7948
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5318 - accuracy: 0.8015
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5218 - accuracy: 0.7980
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5137 - accuracy: 0.7975
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5128 - accuracy: 0.7909
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4993 - accura

In [ ]:
#Prediction
print(ann.predict(sc.transform([[1, 0, 1, 600, 1, 40, 3, 60000, 2, 1, 1, 1, 50000]])))

[[0.05662373]]


In [ ]:
#Prediction using test data
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm.)
accuracy_score(y_test, y_pred)

[[1501   94]
 [ 198  207]]


0.854